/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ikbal.app.ui;

import com.ikbal.app.ui.component.tambahan.JTabbedPaneCloseButton;
import com.ikbal.app.ui.panel.master.UIKaryawan;
import com.ikbal.app.ui.panel.master.UIKendaraan;
import com.ikbal.app.ui.panel.master.UIPelanggan;
import com.ikbal.app.ui.panel.master.UIPengguna;
import com.ikbal.app.ui.panel.master.UISparepart;
import com.ikbal.app.ui.panel.transaksi.UIWorkOrder;
import java.awt.Button;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author lenovo
 */
public class UIMenuUtama extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    private UIPelanggan pelanggan;
    private UIKendaraan kendaraan;
    private UIKaryawan karyawan;
    private UISparepart sparepart;

    /**
     * Creates new form UIMenuUtama
     */
    public UIMenuUtama() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new com.ikbal.app.ui.component.tambahan.JTabbedPaneCloseButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mIPengguna = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        nmPelanggan = new javax.swing.JMenuItem();
        mnKendaraan = new javax.swing.JMenuItem();
        mnSparepart = new javax.swing.JMenuItem();
        mnKaryawan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Monitoring Bengkel");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setName("UIMenuUtama"); // NOI18N
        setPreferredSize(new java.awt.Dimension(3066, 416));

        jMenu1.setText("File");

        mIPengguna.setText("Pengguna");
        mIPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIPenggunaActionPerformed(evt);
            }
        });
        jMenu1.add(mIPengguna);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Master");

        nmPelanggan.setText("Pelanggan");
        nmPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(nmPelanggan);

        mnKendaraan.setText("Kendaraan");
        mnKendaraan.setName("mnKendaraan"); // NOI18N
        mnKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKendaraanActionPerformed(evt);
            }
        });
        jMenu3.add(mnKendaraan);

        mnSparepart.setText("Sparepart");
        mnSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSparepartActionPerformed(evt);
            }
        });
        jMenu3.add(mnSparepart);

        mnKaryawan.setText("Karyawan");
        mnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(mnKaryawan);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Transaksi");

        jMenuItem1.setText("Buat Perintah Kerja");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Laporan");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIPenggunaActionPerformed
        this.pengguna = new UIPengguna();
        tabPanel.addTab("Pengguna", pengguna);
        tabPanel.setSelectedComponent(pengguna);
    }//GEN-LAST:event_mIPenggunaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.wo = new com.ikbal.app.ui.panel.transaksi.UIWorkOrder();
        tabPanel.addTab("Perintah Kerja", wo);
        tabPanel.setSelectedComponent(wo);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void nmPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmPelangganActionPerformed
        this.pelanggan = new com.ikbal.app.ui.panel.master.UIPelanggan();
        tabPanel.addTab("Pelanggan", pelanggan);
        tabPanel.setSelectedComponent(pelanggan);
    }//GEN-LAST:event_nmPelangganActionPerformed

    private void mnKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKendaraanActionPerformed
        this.kendaraan = new com.ikbal.app.ui.panel.master.UIKendaraan();
        tabPanel.addTab("Kendaraan", kendaraan);
        tabPanel.setSelectedComponent(kendaraan);
    }//GEN-LAST:event_mnKendaraanActionPerformed

    private void mnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKaryawanActionPerformed
        this.karyawan = new com.ikbal.app.ui.panel.master.UIKaryawan();
        tabPanel.addTab("Karyawan", karyawan);
        tabPanel.setSelectedComponent(karyawan);
    }//GEN-LAST:event_mnKaryawanActionPerformed

    private void mnSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSparepartActionPerformed
        this.sparepart = new com.ikbal.app.ui.panel.master.UISparepart();
        tabPanel.addTab("Sparepart", sparepart);
        tabPanel.setSelectedComponent(sparepart);
    }//GEN-LAST:event_mnSparepartActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UIMenuUtama().setVisible(true);
            }
        });
        
        
    }

    private UIPengguna pengguna;
    private UIWorkOrder wo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mIPengguna;
    private javax.swing.JMenuItem mnKaryawan;
    private javax.swing.JMenuItem mnKendaraan;
    private javax.swing.JMenuItem mnSparepart;
    private javax.swing.JMenuItem nmPelanggan;
    /*
    private org.netbeans.modules.form.InvalidComponent tabPanel;
    */
    private com.ikbal.app.ui.component.tambahan.JTabbedPaneCloseButton tabPanel;
    // End of variables declaration//GEN-END:variables
    
}
